# The log level for the main application logger.
log_level = "info"

# The username and password for the basic auth.
username = "scalr"

# The credentials for the MinIO server.
# XXX: Public keys for the public MinIO service (play.min.io) provided by
# the MinIO team for testing. It's safe to share it publicly.
minio_host = "play.min.io"
minio_access_key = "Q3AM3UQ867SPQQA43P2F"
minio_secret_key = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
