log_level = "debug"

# XXX: Public keys for the public MinIO service provided by
# the MinIO team for testing.
minio_access_key = "Q3AM3UQ867SPQQA43P2F"
minio_secret_key = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
